-- MangosSuperUI_Placer Catalog
-- Auto-generated by MangosSuperUI on 2026-04-07 01:32:38 UTC
-- 3 custom game object(s)

MSUI_CATALOG = {
    [987658] = { name = "Equipment Crates", type = 5, displayId = 36, spawns = 0, desc = "Decoration" },
    [3000491] = { name = "Kroshius' Remains", type = 5, displayId = 1268, spawns = 1, desc = "Decoration" },
    [3000492] = { name = "Test Shrine Songflower Nico", type = 22, displayId = 6873, spawns = 2, desc = "Casts Songflower Serenade (single use)" },
}

-- Type name lookup for the addon UI
MSUI_TYPE_NAMES = {
    [0] = "Door", [1] = "Button", [2] = "Quest Giver", [3] = "Chest",
    [5] = "Generic", [6] = "Trap", [7] = "Chair", [8] = "Spell Focus",
    [9] = "Text", [10] = "Goober", [11] = "Transport", [13] = "Camera",
    [15] = "MO Transport", [17] = "Fishing Node", [18] = "Ritual",
    [19] = "Mailbox", [20] = "Auction House", [22] = "Spell Caster",
    [23] = "Meeting Stone", [24] = "Flag Stand", [25] = "Fishing Hole",
    [26] = "Flag Drop", [29] = "Capture Point", [30] = "Aura Generator",
    [31] = "Dungeon Difficulty",
}
